

#
amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
#  accessKey:  AKIAUUD57ECHDDMP3CAQ
  accessKey: AKIAUUD57ECHJ566CDBL
#  secretKey:  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
  secretKey: X6ucbrNq8USXPYyMrcoEJOXNmi9NefnspWS/OMun
  bucketName: shopperzoid.product

